* CBIL

  This repository is a shared resource created by the [[https://www.cbil.upenn.edu/][Computational Biology and Informatics Laboratory (CBIL)]] in Penn's Institute for Biomedical Informatics.  It contains a variety of scripts and packages for bioinformatics applications and other general purpose code.

** Dependencies

   + yarn / npm / ant
   + environment variables for GUS_HOME and PROJECT_HOME
   + Internal Dependencies
     + [[https://github.com/VEuPathDB/install][install]]

** Installation instructions.

   + bld CBIL

** Manifest

   + Bio :: library of value objects for biologically meaningful entities and file types.  deprecated in favor of Bioperl.
   + Cider :: set of packages that help generate a website with using page body parts, a navbar, and a configurable look-and-feel.  
   + CSP :: CBIL Style Police (CSP) is a Perl package for generating HTML pages and forms in a principled manner.   
   + HQ :: library of value objects used when computing hierarchical entropy values
   + ISA :: readers and library of value objects for [[https://isa-specs.readthedocs.io/en/latest/isatab.html][ISA-Tab]] Format
   + StudyAssayResults :: Modules for analyzing expression data (Microarray and RNASeq) and other data types.  
   + Util :: Helper modules for a variety of tasks
